### ISSUE TITLE
Some Error in Ubuntu 18.04

### ISSUE THREAD

**Issue by AshSwing** [RainingComputers/whipFTP#3]
File "/usr/share/whipFTP/whipFTP.py", line 1185, in <module>
    root.tk.eval('package require tkdnd')
_tkinter.TclError: couldn't load file "/usr/share/whipFTP/TkDND/libtkdnd2.8.so": /usr/share/whipFTP/TkDND/libtkdnd2.8.so: wrong ELF class: ELFCLASS32

**Comment by RainingComputers** [comment]
I may need to make a separate 64bit version.

**Comment by RainingComputers** [comment]
I will release a new version with a patch.

**Comment by RainingComputers** [comment]
I released a new version: https://github.com/RainingComputers/whipFTP/releases
